logging:
  file: logs/serviceya.log
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    sensitive: false
    enabled: true
    time-to-live: 20000

info:
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@
    name: @project.name@

spring:

  h2:
    console:
      enabled: true

  datasource:
    initialize: true

  jpa:
    show-sql: true

google:
  maps:
    key: AIzaSyBNJvYQ-t6dymsHr6bI6UtSH9MlB5ujlTk